### ISSUE TITLE
using encoding/xml/ to parse html

### ISSUE THREAD

**Issue by sztanpet** [dpw/vendetta#5]
this will not work

https://chitin.io/ has the necessary tags for example, but it fails badly, the parser in go get itself handles it specially anyway

**Comment by dpw** [comment]
Hi.  Can you provide an example that works with `go  get` but fails with vendetta?  I'm not familiar with chitin.io, so I'm not sure I'm doing the right thing.

I tried to `go get chitin.io/chitin` as suggested at https://chitin.io/code/ , but I get

```
$ go get chitin.io/chitin
package chitin.io/chitin: unrecognized import path "chitin.io/chitin"
```

with go 1.5.1.

The code used by vendetta to parse import tags is borrowed from go, so there shouldn't be a case where it works with `go get` but not with vendetta.  But of course it's possible I broke something when extracting it from the go code base.

**Comment by sztanpet** [comment]
I was purely rehashing this https://github.com/golang/go/issues/13683 ticket, I did not make sure the problem actually exist shame on me :(

**Comment by dpw** [comment]
I see.  Thanks for the link.

I guess this could be fixed in vendetta (there's a HTML5 parser at https://godoc.org/golang.org/x/net/html, so it might not be too hard).  But I'm reluctant to let the reporoot code in vendetta diverge from that in the go source tree, as that would make it hard to merge any changes they make.  My preference would be to see this addressed upstream, and I'll take the fix from there.  So I'm going to close this issue.

(The difficulty in fixing it upstream is that it would require the HTML5 parser to be added to the go standard library.  I've no idea how likely/unlikely that is.)

I'd still be open minded if anyone wants to submit a PR for this.
