### ISSUE TITLE
Add project name inferring for any git repo

### ISSUE THREAD

**Issue by solher** [dpw/vendetta#7]
Currently, it seems that project name inferring only works for projects hosted on Github.
Could you add the support for any host (eg. ssh://git@git.foobar.com:8080/foo/bar.git) ?

**Comment by dpw** [comment]
The problem with that suggestion is: how to reliably derive the golang project name from the git URL? In the example you give, we might guess `git.foobar.com/foo/bar`, but it could easily be `foobar.com/foo/bar`, and in general it could be anything at all.

If the inferred project name is wrong, and the project has multiple packages with dependencies between them, then vendetta will try to satisfy those dependencies by adding the project as a submodule of itself.  This would be quite annoying.  So inferred project names should be reliable, not just a good guess.

I have a couple of other ideas for how to infer project names:
- If GOPATH is set, vendetta could see if the project directory is under some element of it.  For example, if `GOPATH=/blah`, and the project directory is `/blah/src/foobar.com/foo/bar`, then the project name is `foobar.com/foo/bar`.
- Go has a [canonical import paths](https://golang.org/doc/go1.4#canonicalimports) feature.  But I don't see much go code using this.

Would either of these ideas solve the problem in your context?

**Comment by solher** [comment]
I think that in general, people respect path/naming conventions. The git URL could be `titi.tutu/toto` or `foobar.com/foo/bar`, will not the packages be `titi.tutu/toto` or `foobar.com/foo/bar` ?

But yes you could definitely use the canonical import path.
I'm already using it with https://github.com/CenturyLinkLabs/golang-builder.

I love your project btw !

**Comment by dpw** [comment]
> think that in general, people respect path/naming conventions. The git URL could be titi.tutu/toto or foobar.com/foo/bar, will not the packages be titi.tutu/toto or foobar.com/foo/bar ?

In general, package names are not related to git remote URLs.  This is not because people don't respect conventions, but because the go package retrieval and git code hosting don't necessarily coincide.  It may look like they do, almost, in a case where a git remote URL `git@github.com:user/proj.git` corresponds to a package name `github.com/user/proj`.  But you only have to fork a project on github for `git@github.com:me/proj.git` to correspond to `github.com/them/proj`.  And there are contexts where they have even less in common (e.g. the git repo for `golang.org/x/net` is at `https://go.googlesource.com/net`).

**Comment by solher** [comment]
You're totally right. The canonical import path seems to be a good solution in that case. That why it was created.

**Comment by dpw** [comment]
Since this issue was opened, I've improved project name inference in a few ways:
- If you set GOPATH, and the project directory is under some element of the GOPATH, then the project name is derived from its path.
- If a source file in your project has an import comment, that can imply a package name for the top-level package of the project.
- Sometimes we don't need a project name, because all the source files are in package `main`.

I'm hoping that these approaches, combined with the existing approach of looking for git remotes on github, will cover most users. (Because I don't have any further ideas on this!)

Please let me know if you are now able to avoid using the `-n` in the situation where you had to before, and close this issue if so.
