### ISSUE TITLE
Test dependencies missing?

### ISSUE THREAD

**Issue by michaelsauter** [dpw/vendetta#8]
I wanted to switch to Go's vendoring feature for a while for my project and decided vendetta would be a good tool to get going quickly. Overall, very happy with it! Thanks.

However, I think vendetta missed the dependencies in tests. You can see this on the branch where I setup the vendoring: https://github.com/michaelsauter/crane/pull/263.

The first commit c30331 is the result of running just `vendetta` in the project root. Then, tests failed and I had to manually add a dependency for the tests, `testify` in f8f220.

Is this a bug or intentional? Would be nice to add least have a switch to add those dependencies too.

**Comment by dpw** [comment]
Vendetta is supposed to add dependencies of tests in the top-level project.  It deliberately does not add dependencies of tests in dependencies (because I've seen projects where doing so would greatly increases the set of dependencies).  But in your case, testify is referred to from the top-level project, not from a dependency, so you have found a bug.

What's happening for your project is that vendetta processes `main.go` first, sees that it depends on `github.com/michaelsauter/crane/crane`, and then processes that package _as if it was a dependency_.  So it ignores the test imports found there.  That's clearly wrong.

Thanks for reporting this.

**Comment by dpw** [comment]
I've pushed a fix for this.  Please confirm that it works for you, and if so, close this issue.

**Comment by dpw** [comment]
No response, so closing.

**Comment by michaelsauter** [comment]
@dpw Sorry, I forgot about it. Just tested it now with an updated version of vendetta and it works. Thanks for the fix!
